import {HABITS,today,fresh,number,bmi,ratio,portion,recipeTotals,validateState,parseBackup,backup} from './core.js';
import {openDB,read,write} from './db.js';
const $=s=>document.querySelector(s);
function el(tag,attrs={},...children){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else if(v!==false&&v!==null&&v!==undefined)n.setAttribute(k,v===true?'':v);}for(const c of children.flat(Infinity)){if(c!==null&&c!==undefined)n.append(c instanceof Node?c:document.createTextNode(String(c)));}return n;}
const link=(text,href,cls)=>el('a',{href,class:cls},text);
const external=(text,href)=>el('a',{href,target:'_blank',rel:'noopener noreferrer'},text+' ↗');
const button=(text,fn,cls)=>el('button',{type:'button',class:cls,onclick:fn},text);
const fmt=(n,d=1)=>n===null||n===undefined?'Sin dato':new Intl.NumberFormat('es',{maximumFractionDigits:d}).format(n);
const dateFmt=s=>new Date(s+'T12:00:00').toLocaleDateString('es',{day:'numeric',month:'short',year:'numeric'});
const field=(label,node)=>el('label',{class:'field'},label,node);
const input=(name,value='',extra={})=>el('input',{name,value:value??'',...extra});
const pageHeading=(eyebrow,title,description)=>el('div',{},el('p',{class:'eyebrow'},eyebrow),el('h1',{},title),el('p',{class:'subtitle'},description));
const symbols={'Frutas':'🍐','Verduras':'🥬','Legumbres':'🫘','Cereales':'🌾','Tubérculos':'🥔','Frutos secos y semillas':'🌰','Aceites':'🫒','Proteínas':'🍳','Lácteos':'🥛','Bebidas':'💧'};
let state=fresh(),catalog,dbReady=false,busy=false,dirty=false,currentHash=location.hash||'#hoy',browseType='foods',search='',group='',onlyFavorites=false,learnFavorites=false,registration,installPrompt;
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
function showError(error){toast(error.message||String(error));}
async function confirmAction(title,text){const d=$('#confirm');$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;d.returnValue='cancel';return new Promise(resolve=>{d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true});d.showModal();});}
function applyTheme(){const t=state.profile.theme;document.body.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):t;$('#theme').setAttribute('aria-label',document.body.dataset.theme==='dark'?'Cambiar a tema claro':'Cambiar a tema oscuro');}
async function commit(next,message='Guardado en este dispositivo.'){if(!dbReady){showError(Error('El almacenamiento no está disponible. No se guardó el cambio.'));return false;}if(busy){toast('Esperá a que termine la operación anterior.');return false;}busy=true;try{next=validateState(next);await write(next);state=next;dirty=false;applyTheme();if(message)toast(message);return true;}catch(e){showError(e);return false;}finally{busy=false;}}
const clone=()=>structuredClone(state);
function markForm(form){form.addEventListener('input',()=>dirty=true);return form;}
function favorite(id){return button(state.favorites.includes(id)?'♥':'♡',async e=>{e.preventDefault();if(dirty&&!await confirmAction('Hay cambios sin guardar','¿Descartar esos cambios para guardar el favorito?'))return;const next=clone();next.favorites=next.favorites.includes(id)?next.favorites.filter(x=>x!==id):[...next.favorites,id];if(await commit(next,'Favoritos actualizados.'))render(false);},'favorite');}
function favButton(id){const b=favorite(id);b.setAttribute('aria-label',(state.favorites.includes(id)?'Quitar de':'Añadir a')+' favoritos');b.setAttribute('aria-pressed',String(state.favorites.includes(id)));return b;}
function source(id){const s=catalog.sources.find(x=>x.id===id);return el('div',{class:'source-item'},external(s.title,s.url),el('p',{class:'caption'},`${s.kind} · Revisión documental: ${dateFmt(s.reviewed)}`),el('p',{class:'caption'},s.limits));}
function empty(title,text){return el('div',{class:'empty'},el('span',{'aria-hidden':'true'},'♧'),el('h3',{},title),el('p',{},text));}
function home(){
 const date=today(),entry=state.entries.find(e=>e.date===date),active=HABITS.filter(h=>state.habits.includes(h.id));
 const root=el('div',{},pageHeading('PASO A PASO','Hoy, a tu ritmo.','Pequeños hábitos. Espacio para aprender. Sin buscar la perfección.'));
 root.append(el('section',{class:'hero'},el('div',{},el('p',{class:'eyebrow'},'UNA IDEA PARA HOY'),el('h2',{},'Sumar algo bueno también es empezar.'),el('p',{},'Una verdura, una receta sencilla o un momento para planificar. Elegí lo que tenga sentido para vos.'),link('Explorar alimentos  →','#explorar')),el('img',{src:'assets/bowl.svg',alt:'Ilustración de un cuenco con verduras y cereales',width:340,height:240})));
 if(!state.entries.length)root.append(el('div',{class:'onboarding'},el('p',{},'Para adultos · Podés usar la guía sin registrar peso. Tus datos se guardan en este navegador; un respaldo ayuda a conservarlos.'),link('Cómo funciona','#ajustes')));
 const form=markForm(el('form',{id:'daily-form'}));
 const habitCard=el('section',{class:'card'},el('div',{class:'section-title'},el('h2',{},'Mis pequeños hábitos'),link('Elegir','#habitos')),el('p',{class:'caption'},'Marcá lo que hiciste hoy. Después guardá tu día.'));
 for(const h of active){const cb=input('done',h.id,{type:'checkbox','aria-label':h.title});cb.checked=entry?.done.includes(h.id)||false;habitCard.append(el('label',{class:'habit'},el('span',{class:'habit-emoji','aria-hidden':'true'},h.icon),el('span',{},el('strong',{},h.title),el('small',{},h.detail)),cb));}
 if(!active.length)habitCard.append(empty('A tu elección','Elegí hasta tres hábitos, o usá solo el diario.'));
 const note=el('textarea',{name:'note',maxlength:2000,placeholder:'¿Qué te resultó práctico? ¿Qué te gustaría repetir?',rows:4},entry?.note||'');
 const noteCard=el('section',{class:'card'},el('h2',{},'Un momento para vos'),field('Nota del día · opcional',note),el('p',{class:'caption'},'No hace falta registrar lo que comiste ni contar calorías.'));
 form.append(el('div',{class:'grid two'},habitCard,noteCard));
 if(!state.profile.hideMeasurements){const details=el('details',{},el('summary',{},'Registrar peso o cintura · opcional'),el('p',{class:'caption'},'No necesitás completar estas medidas para usar la app.'),el('div',{class:'form-grid'},field('Peso (kg)',input('weight',entry?.weight,{inputmode:'decimal',placeholder:'Ej. 80,5'})),field('Cintura (cm)',input('waist',entry?.waist,{inputmode:'decimal',placeholder:'Ej. 90'}))));form.append(details);}
 form.append(el('div',{class:'actions'},el('button',{type:'submit',class:'primary'},entry?'Actualizar mi día':'Guardar mi día'),el('span',{class:'caption'},entry?'Ya tenés un registro de hoy. Podés modificarlo.':'Solo en este dispositivo.')));
 form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);try{const next=clone();const updated={date,planned:[...state.habits],done:fd.getAll('done'),note:fd.get('note').trim(),weight:state.profile.hideMeasurements?entry?.weight??null:number(fd.get('weight'),20,400,'Peso'),waist:state.profile.hideMeasurements?entry?.waist??null:number(fd.get('waist'),30,250,'Cintura')};next.entries=next.entries.filter(e=>e.date!==date).concat(updated);if(await commit(next))render(false);}catch(err){showError(err);}});
 root.append(form,el('section',{class:'section'},el('div',{class:'section-title'},el('h2',{},'Para acompañar tu día'),link('Ver biblioteca','#aprender')),el('div',{class:'grid two'},el('article',{class:'card peach'},el('p',{class:'eyebrow'},'LECTURA BREVE · 2 MIN'),el('h3',{},'Porciones sin reglas rígidas'),el('p',{},'Una referencia para entender los alimentos, no una medida de lo que deberías comer.'),link('Leer con calma  →','#articulo/article-3')),el('article',{class:'card'},el('p',{class:'eyebrow'},'COCINA SENCILLA'),el('h3',{},'Ensalada tibia de lentejas'),el('p',{},'15 minutos con legumbres ya cocidas. Una idea económica y flexible.'),link('Ver la receta  →','#receta/recipe-1')))));
 return root;
}
function habits(){const form=markForm(el('form',{class:'card reading'},el('h2',{},'Elegí hasta tres'),el('p',{class:'muted'},'Son propuestas de organización, no metas clínicas. Los registros anteriores se conservarán.')));for(const h of HABITS){const cb=input('habits',h.id,{type:'checkbox'});cb.checked=state.habits.includes(h.id);form.append(el('label',{class:'habit'},el('span',{class:'habit-emoji','aria-hidden':'true'},h.icon),el('span',{},el('strong',{},h.title),el('small',{},h.detail)),cb));}form.append(el('button',{class:'primary',type:'submit'},'Guardar hábitos'));form.onsubmit=async e=>{e.preventDefault();const next=clone();next.habits=new FormData(form).getAll('habits');if(await commit(next))location.hash='hoy';};return el('div',{},pageHeading('TU ELECCIÓN','Un cambio pequeño.','Podés elegir menos de tres, o ninguno.'),form);}
function card(item,type){const route=type==='foods'?'alimento':type==='recipes'?'receta':'articulo';return el('article',{class:'card food-card'},el('span',{class:'food-symbol','aria-hidden':'true'},type==='foods'?symbols[item.group]:type==='recipes'?'🍲':'▤'),favButton(item.id),el('p',{class:'eyebrow'},type==='foods'?item.group:type==='recipes'?item.tags.join(' · '):'LECTURA BREVE'),el('h3',{},link(item.name,`#${route}/${item.id}`)),el('p',{},item.state||item.description),el('span',{class:'caption'},type==='foods'?'Ficha con fuente USDA':type==='recipes'?`${item.minutes} min · ${item.servings} porción${item.servings>1?'es':''}`:`${item.minutes} min · Fuentes incluidas`));}
function browse(){
 const root=el('div',{},pageHeading('CURIOSIDAD EN LA MESA','Explorar, sin etiquetas.','Ideas para conocer los alimentos y hacerlos parte de tu día.'));
 const tabs=el('div',{class:'browse-tabs','aria-label':'Tipo de contenido'});for(const[type,title]of[['foods','Alimentos · 50'],['recipes','Recetas · 10']]){const b=button(title,()=>{browseType=type;render(false);});b.setAttribute('aria-pressed',String(type===browseType));tabs.append(b);}const fav=button('♡ Mis favoritos',()=>{onlyFavorites=!onlyFavorites;render(false);});fav.setAttribute('aria-pressed',String(onlyFavorites));tabs.append(fav);root.append(tabs);
 const searchInput=input('search',search,{type:'search',placeholder:'Buscar por nombre o ingrediente…',id:'search'});
 const groupSelect=el('select',{'aria-label':'Grupo de alimentos'},el('option',{value:''},'Todos los grupos'),...[...new Set(catalog.foods.map(f=>f.group))].map(g=>el('option',{value:g},g)));groupSelect.value=group;
 const result=el('div',{class:'grid three',id:'results'}),count=el('p',{class:'caption',role:'status'});
 function update(){search=searchInput.value;group=groupSelect.value;const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=norm(search);let items=catalog[browseType].filter(x=>(!onlyFavorites||state.favorites.includes(x.id))&&(!group||browseType!=='foods'||x.group===group)&&norm(x.name+' '+(x.state||'')+' '+(x.ingredients?.map(i=>catalog.foods.find(f=>f.id===i.food).name).join(' ')||'')).includes(q));result.replaceChildren(...items.map(x=>card(x,browseType)));if(!items.length)result.append(empty('No encontramos coincidencias','Probá otra palabra o guardá una ficha en favoritos.'));count.textContent=`${items.length} ${browseType==='foods'?'alimentos':'recetas'}`;}
 searchInput.oninput=update;groupSelect.onchange=update;root.append(el('div',{class:'filters'},field('Buscar',searchInput),browseType==='foods'?field('Grupo',groupSelect):el('p',{class:'caption'},'Tiempos con ingredientes cocidos listos.')),count,result);update();return root;
}
function nutrients(values){return el('div',{class:'nutrients'},...Object.entries({energy:['Energía','kcal'],protein:['Proteína','g'],carbs:['Carbohidratos','g'],fat:['Grasas','g'],fiber:['Fibra','g']}).map(([k,[label,unit]])=>el('div',{class:'nutrient'},el('strong',{},fmt(values[k],k==='energy'?0:1)+(values[k]===null?'':' '+unit)),el('span',{},label))));}
function foodDetail(id){const f=catalog.foods.find(x=>x.id===id);if(!f)return notFound();const grams=input('grams',f.serving,{inputmode:'decimal',id:'grams'}),n=el('div',{'aria-live':'polite'});function calc(){try{const g=number(grams.value,1,2000,'Cantidad');n.replaceChildren(g===null?el('p',{},'Ingresá una cantidad.'):nutrients(portion(f.nutrients,g)));}catch(e){n.replaceChildren(el('p',{class:'error'},e.message));}}grams.oninput=calc;calc();const favoriteButton=favButton(f.id);favoriteButton.className='icon-btn';return el('div',{},link('← Volver a explorar','#explorar','back'),pageHeading(f.group,f.name,f.state),el('div',{class:'card reading'},el('div',{class:'heading-row'},el('h2',{},'Una referencia, no una regla'),favoriteButton),el('p',{class:'muted'},'Cantidad de parte comestible. La porción inicial es un ejemplo de cálculo, no una recomendación individual.'),field('Cantidad (gramos)',grams),n,el('p',{class:'caption'},'Valores aproximados. Varían según origen y preparación. «Sin dato» no equivale a cero.'),el('details',{},el('summary',{},'Valores por 100 g y procedencia'),nutrients(f.nutrients),el('p',{class:'caption'},f.sourceDescription),external('Registro USDA '+f.sourceId,f.sourceUrl),el('p',{class:'caption'},'SR Legacy · Datos de 2018 · Revisión: '+dateFmt(f.reviewed))),source('usda')));}
function recipeDetail(id){const r=catalog.recipes.find(x=>x.id===id);if(!r)return notFound();const favoriteButton=favButton(r.id);favoriteButton.className='icon-btn';return el('div',{},link('← Volver a recetas','#explorar','back'),pageHeading('COCINA SENCILLA',r.name,r.description),el('div',{class:'heading-row'},el('span',{class:'pill'},`${r.minutes} min · ${r.servings} porción${r.servings>1?'es':''}`),favoriteButton),el('div',{class:'detail-layout'},el('section',{class:'card'},el('h2',{},'Paso a paso'),el('ol',{class:'list'},...r.steps.map(s=>el('li',{},s))),el('p',{class:'caption'},'El tiempo supone que los ingredientes descritos como cocidos ya están preparados.')),el('section',{class:'card peach'},el('h2',{},'Ingredientes'),el('ul',{class:'list'},...r.ingredients.map(i=>{const f=catalog.foods.find(x=>x.id===i.food);return el('li',{},link(f.name,'#alimento/'+f.id),` · ${i.grams} g`,el('div',{class:'caption'},f.state));})))),el('section',{class:'section card'},el('h2',{},'Estimación por porción'),nutrients(recipeTotals(r,catalog.foods)),el('p',{class:'caption'},'Suma de ingredientes USDA dividida por porciones. No incluye ingredientes extra ni ajustes por pérdidas de cocción; no es un análisis de laboratorio.'),el('p',{},'Alérgenos indicativos: '+(r.allergens.join(', ')||'Sin alérgenos principales identificados en la formulación. Revisá envases y contaminación cruzada.')),el('p',{},r.substitution),source('usda')));}
function learn(){const b=button(learnFavorites?'Ver todas las lecturas':'♡ Mis lecturas favoritas',()=>{learnFavorites=!learnFavorites;render(false);});b.setAttribute('aria-pressed',String(learnFavorites));const articles=catalog.articles.filter(a=>!learnFavorites||state.favorites.includes(a.id));return el('div',{},pageHeading('UN POCO DE CONTEXTO','Aprender con calma.','Lecturas breves, fuentes visibles y espacio para tus propias decisiones.'),el('div',{class:'browse-tabs'},b),articles.length?el('div',{class:'grid two'},...articles.map(a=>card(a,'articles'))):empty('Tu biblioteca personal','Guardá una lectura con el corazón para encontrarla aquí.'),el('p',{class:'caption section'},'Revisión documental: octubre de 2026. Sin revisión clínica independiente. ',link('Consultar fuentes y criterios','#fuentes')));}
function articleDetail(id){const a=catalog.articles.find(x=>x.id===id);if(!a)return notFound();const f=favButton(a.id);f.className='icon-btn';return el('article',{class:'reading'},link('← Volver a aprender','#aprender','back'),pageHeading('LECTURA BREVE · 2 MIN',a.name,a.description),f,...a.sections.map(s=>el('section',{},el('h2',{},s.title),el('p',{},s.text))),el('div',{class:'notice'},`Contenido educativo original · ${a.status} · ${dateFmt(a.reviewed)}. Próxima revisión prevista: ${dateFmt(a.reviewDue)}.`),source(a.source));}
function chart(entries,key,label){const points=entries.filter(e=>e[key]!==null);if(!points.length)return empty('Todavía no hay mediciones','Podés registrar una medida si te resulta útil. También podés usar solo los hábitos.');const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 220');svg.setAttribute('class','chart');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${label}: ${points.length} mediciones. Los valores exactos están en la tabla de abajo.`);function s(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;svg.append(n);return n;}const vals=points.map(e=>e[key]),lo=Math.min(...vals)-1,hi=Math.max(...vals)+1,start=Date.parse(points[0].date),end=Date.parse(points.at(-1).date);const coords=points.map(e=>[points.length===1?320:55+(Date.parse(e.date)-start)/(end-start||1)*520,170-(e[key]-lo)/(hi-lo)*135]);for(let i=0;i<3;i++){const y=35+i*67.5;s('line',{x1:50,x2:580,y1:y,y2:y});s('text',{x:4,y:y+4},fmt(hi-(hi-lo)*i/2));}s('path',{d:coords.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ')});coords.forEach(([x,y])=>s('circle',{cx:x,cy:y,r:4}));s('text',{x:55,y:205},dateFmt(points[0].date));if(points.length>1)s('text',{x:580,y:205,'text-anchor':'end'},dateFmt(points.at(-1).date));return svg;}
function progress(){const entries=[...state.entries].sort((a,b)=>a.date.localeCompare(b.date));const recent=entries.filter(e=>(Date.parse(today())-Date.parse(e.date))/86400000<7);const done=recent.reduce((a,e)=>a+e.done.length,0),planned=recent.reduce((a,e)=>a+e.planned.length,0);const root=el('div',{},pageHeading('MIRAR EL CAMINO','Tu progreso, sin apuro.','Los días sin registro son espacios en blanco, no fallos.'));
 root.append(el('section',{class:'card'},el('h2',{},'Últimos siete días'),el('div',{class:'stat-row'},el('div',{class:'stat'},el('strong',{},recent.length),el('span',{},'días con registro')),el('div',{class:'stat'},el('strong',{},`${done} / ${planned}`),el('span',{},'hábitos marcados / planificados')),el('div',{class:'stat'},el('strong',{},planned?fmt(done/planned*100,0)+' %':'—'),el('span',{},'sobre los días registrados'))),el('p',{class:'caption'},'Se conserva la selección de hábitos de cada día guardado. No es una evaluación de salud.')));
 if(!state.profile.hideMeasurements){for(const[key,label,unit]of[['weight','Peso','kg'],['waist','Cintura','cm']])root.append(el('section',{class:'section card'},el('h2',{},label+' · '+unit),chart(entries,key,label)));const last=entries.filter(e=>e.weight!==null||e.waist!==null).at(-1);const height=state.profile.height;root.append(el('section',{class:'card section'},el('h2',{},'Cálculos informativos'),el('p',{class:'caption'},'Se usa la última entrada con medidas y tu altura actual. No mostramos diagnósticos ni categorías de riesgo.'),el('div',{class:'stat-row'},el('div',{class:'stat'},el('strong',{},fmt(last?bmi(last.weight,height):null)),el('span',{},'IMC · kg/m²')),el('div',{class:'stat'},el('strong',{},fmt(last?ratio(last.waist,height):null,2)),el('span',{},'cintura / altura'))),el('p',{class:'caption'},height?`Altura: ${fmt(height)} cm. ${last?'Registro: '+dateFmt(last.date):''}`:'Para calcularlos, añadí tu altura en ajustes.'),link('Altura y preferencias','#ajustes'),el('p',{class:'caption'},'El IMC no distingue músculo de grasa. La cintura/altura requiere contexto; NICE la utiliza especialmente con IMC menor de 35. No interpretar durante el embarazo.')));}
 const section=el('section',{class:'section card'},el('div',{class:'section-title'},el('h2',{},'Tu diario'),link('Añadir o editar fecha','#registro')));if(entries.length){const table=el('table',{},el('caption',{class:'sr-only'},'Registros personales por fecha'),el('thead',{},el('tr',{},...['Fecha','Hábitos',...(!state.profile.hideMeasurements?['Peso (kg)','Cintura (cm)']:[]),'Acciones'].map(h=>el('th',{scope:'col'},h)))),el('tbody',{},...entries.slice().reverse().map(e=>el('tr',{},el('td',{},dateFmt(e.date)),el('td',{},e.done.length+' / '+e.planned.length),...(!state.profile.hideMeasurements?[el('td',{},fmt(e.weight)),el('td',{},fmt(e.waist))]:[]),el('td',{},link('Ver / editar','#registro/'+e.date))))));section.append(el('div',{class:'table-wrap'},table));}else section.append(empty('El primer paso puede ser hoy','Guardá un hábito o una nota desde la pantalla Hoy.'));root.append(section);return root;}
function editEntry(date){const editing=Boolean(date);date=date||today();const existing=editing?state.entries.find(e=>e.date===date):undefined;const form=markForm(el('form',{class:'card reading'}));const dateInput=input('date',date,{type:'date',max:today(),min:'1900-01-01',required:true});if(existing)dateInput.readOnly=true;form.append(field('Fecha',dateInput));const planned=existing?.planned||state.habits;for(const id of planned){const h=HABITS.find(h=>h.id===id),cb=input('done',id,{type:'checkbox'});cb.checked=existing?.done.includes(id)||false;form.append(el('label',{class:'habit'},h.title,cb));}if(!state.profile.hideMeasurements)form.append(el('div',{class:'form-grid'},field('Peso (kg) · opcional',input('weight',existing?.weight,{inputmode:'decimal'})),field('Cintura (cm) · opcional',input('waist',existing?.waist,{inputmode:'decimal'}))));form.append(field('Nota · opcional',el('textarea',{name:'note',maxlength:2000},existing?.note||'')),el('button',{class:'primary',type:'submit'},'Guardar registro'));
 form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);try{const d=fd.get('date');if(!existing&&state.entries.some(e=>e.date===d)){toast('Ya existe esa fecha. Abrila desde el diario para editarla.');return;}const next=clone();next.entries=next.entries.filter(e=>!existing||e.date!==date).concat({date:d,planned:[...planned],done:fd.getAll('done'),note:fd.get('note').trim(),weight:state.profile.hideMeasurements?existing?.weight??null:number(fd.get('weight'),20,400,'Peso'),waist:state.profile.hideMeasurements?existing?.waist??null:number(fd.get('waist'),30,250,'Cintura')});if(await commit(next))location.hash='progreso';}catch(err){showError(err);}};
 if(existing)form.append(button('Eliminar este registro',async()=>{if(await confirmAction('Eliminar registro',`Se eliminará la entrada del ${dateFmt(date)} de este navegador.`)){const next=clone();next.entries=next.entries.filter(e=>e.date!==date);if(await commit(next,'Registro eliminado.'))location.hash='progreso';}},'danger'));
 return el('div',{},link('← Volver al progreso','#progreso','back'),pageHeading('DIARIO PERSONAL',existing?'Tu registro':'Registrar otro día','Los campos de mediciones y notas son opcionales.'),form);
}
function settings(){
 const root=el('div',{},pageHeading('TU ESPACIO, TUS DECISIONES','Ajustes y privacidad.','Sin cuentas, sin anuncios y sin enviar tu diario a nuestros servidores.'));
 const f=markForm(el('form',{class:'card'}));const theme=el('select',{name:'theme'},...['system','light','dark'].map((v,i)=>el('option',{value:v},['Según el sistema','Claro','Oscuro'][i])));theme.value=state.profile.theme;const hide=input('hide','yes',{type:'checkbox'});hide.checked=state.profile.hideMeasurements;f.append(el('h2',{},'A tu manera'),field('Altura (cm) · opcional',input('height',state.profile.height,{inputmode:'decimal',placeholder:'Ej. 170'})),field('Apariencia',theme),el('label',{class:'habit'},'Ocultar peso, cintura y cálculos',hide),el('p',{class:'caption'},'Ocultar no elimina mediciones anteriores. Para borrarlas, editá cada registro o eliminá todos tus datos.'),el('button',{type:'submit',class:'primary'},'Guardar preferencias'));f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);try{const next=clone();next.profile={height:number(fd.get('height'),80,250,'Altura'),theme:fd.get('theme'),hideMeasurements:fd.has('hide')};if(await commit(next))render(false);}catch(err){showError(err);}};
 const file=input('backup','',{type:'file',accept:'.json,application/json',id:'import-file'});file.onchange=async()=>{const selected=file.files[0];if(!selected)return;try{if(selected.size>5_000_000)throw Error('El archivo supera 5 MB.');const next=parseBackup(await selected.text());if(await confirmAction('Reemplazar datos con el respaldo',`Archivo válido: ${next.entries.length} registros y ${next.favorites.length} favoritos. Reemplazará todos los datos personales actuales, incluidas las preferencias. Exportá primero si querés conservarlos.`)){if(await commit(next,'Respaldo restaurado.'))render(false);}}catch(e){showError(e);}finally{file.value='';}};
 const data=el('section',{class:'card'},el('h2',{},'Una copia para vos'),el('p',{},'El respaldo contiene notas y mediciones sin cifrar. Guardalo en un lugar privado. Elegir una carpeta sincronizada puede copiarlo a tu nube.'),button('Exportar respaldo JSON',async()=>{if(dirty){toast('Guardá primero los cambios del formulario.');return;}if(!await confirmAction('Exportar datos personales','Se descargará un archivo sin cifrar con tus registros. No lo publiques ni lo adjuntes a un reporte de error.'))return;const url=URL.createObjectURL(new Blob([backup(state)],{type:'application/json'})),a=el('a',{href:url,download:`mesa-serena-${today()}.json`});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}),el('hr'),field('Restaurar un respaldo',file),el('p',{class:'caption'},'Solo archivos de Mesa Serena. Se comprueban antes de reemplazar tus datos.'),button('Proteger almacenamiento local',async()=>{try{const ok=await navigator.storage?.persist?.();toast(ok?'El navegador concedió almacenamiento persistente. Conservá también un respaldo.':'El navegador no concedió persistencia. Exportá respaldos regularmente.');}catch(e){showError(e);}}));
 root.append(el('div',{class:'grid two'},f,data),el('section',{class:'section card reading'},el('h2',{},'Qué se guarda y dónde'),el('p',{},'Los hábitos, notas, mediciones y favoritos se guardan en IndexedDB, dentro de este navegador y dispositivo. No hay cuenta ni sincronización. Otro navegador tendrá un diario diferente.'),el('p',{},'Borrar datos del navegador, usar modo privado o perder el dispositivo puede borrar el diario. Solicitamos persistencia solo cuando lo elegís; no sustituye un respaldo. No añadimos cifrado propio: quien acceda a tu sesión del dispositivo puede acceder a tus registros.'),el('p',{},'El contenido funciona offline después de descargarse por completo. GitHub Pages puede registrar tu dirección IP al cargar o actualizar la web. Los enlaces externos tienen sus propias políticas; no les enviamos tu diario.'),el('p',{},'Otros proyectos bajo el mismo dominio de GitHub Pages comparten origen web. Los nombres de nuestra base y caché evitan choques accidentales, pero no constituyen aislamiento frente a otros scripts de ese origen.'),el('h3',{},'Instalar y usar sin conexión'),el('p',{},'En navegadores compatibles, usá «Instalar» o la opción «Añadir a pantalla de inicio» del menú. Si esa opción no aparece, podés usar la web normalmente. Esperá el indicador «Disponible sin conexión» antes de desconectarte.'),el('h3',{},'Apoyo voluntario'),el('p',{},'Todas las funciones son gratuitas. No hay funciones premium ni seguimiento de usuarios.'),...(catalog.config.supportUrl?[external('Apoyar el proyecto',catalog.config.supportUrl)]:[]),el('h3',{},'Autoría y contacto'),external(catalog.config.author,catalog.config.authorUrl),el('p',{},external('Reportar un problema sin datos personales',catalog.config.repository+'/issues')),button('Eliminar todos mis datos',async()=>{if(await confirmAction('Eliminar todos mis datos','Se borrarán hábitos personalizados, notas, mediciones, favoritos y preferencias de este navegador. Los respaldos exportados no se borran.')){if(await commit(fresh(),'Datos personales eliminados.'))render(false);}},'danger')));return root;
}
function sourcesPage(){return el('div',{class:'reading'},pageHeading('TRANSPARENCIA','Fuentes y criterios.','Contenido educativo con procedencia visible.'),el('p',{},'Las fichas nutricionales son un subconjunto de USDA SR Legacy 2018. Los consejos y recetas son originales. Las porciones iniciales y los tres hábitos son decisiones de diseño, no prescripciones.'),el('p',{},'Cada lectura identifica una referencia y su fecha de revisión documental. No afirmamos validación clínica independiente ni eficacia demostrada de esta aplicación. Los alérgenos indicados no reemplazan la revisión del envase.'),...catalog.sources.map(s=>source(s.id)),el('p',{class:'caption'},'Código MIT · Contenido editorial CC BY 4.0 · Datos USDA de dominio público con atribución. Las marcas y documentos enlazados mantienen sus derechos.'));}
function notFound(){return el('div',{},pageHeading('PÁGINA NO ENCONTRADA','Volvamos a la mesa.','Este contenido no está en la versión instalada.'),link('Ir a Hoy','#hoy'));}
function render(focus=true){const [route,id]=(location.hash.slice(1)||'hoy').split('/');const views={hoy:home,habitos:habits,explorar:browse,alimento:()=>foodDetail(id),receta:()=>recipeDetail(id),aprender:learn,articulo:()=>articleDetail(id),progreso:progress,registro:()=>editEntry(id),ajustes:settings,fuentes:sourcesPage};try{$('#main').replaceChildren((views[route]||notFound)());}catch(e){$('#main').replaceChildren(empty('No pudimos mostrar esta pantalla','Recargá la página. Tus registros no se borraron.'));showError(e);}const nav=({habitos:'hoy',alimento:'explorar',receta:'explorar',articulo:'aprender',registro:'progreso'})[route]||route;document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===nav)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=($('#main h1')?.textContent||'Guía')+' · Mesa Serena';if(focus){window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
window.addEventListener('hashchange',async()=>{const requested=location.hash;if(dirty){history.replaceState(null,'',currentHash);if(!await confirmAction('Tenés cambios sin guardar','¿Querés descartarlos y cambiar de pantalla?'))return;history.replaceState(null,'',requested);}dirty=false;currentHash=requested;render();});
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
$('#theme').onclick=async()=>{if(dirty){toast('Guardá primero los cambios del formulario.');return;}const next=clone();next.profile.theme=document.body.dataset.theme==='dark'?'light':'dark';await commit(next,'Apariencia actualizada.');};
matchMedia('(prefers-color-scheme:dark)').addEventListener('change',applyTheme);
function status(text,ready=false){$('#offline-status').textContent=text;$('#offline-status').classList.toggle('ready',ready);}
async function checkOffline(){if(!registration?.active)return;try{const c=new MessageChannel();const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('timeout')),4000);c.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data);};registration.active.postMessage({type:'CHECK_READY'},[c.port2]);});status(result.ready?'Disponible sin conexión':'Modo offline incompleto',result.ready);}catch{status('Modo offline por comprobar');}}
async function setupPWA(){if(!('serviceWorker'in navigator)){status('Navegador sin modo offline');return;}try{registration=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;await checkOffline();const waiting=()=>{$('#update-banner').hidden=!registration.waiting;};waiting();registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'){waiting();checkOffline();}});});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem('mesa-updating')){sessionStorage.removeItem('mesa-updating');location.reload();}else checkOffline();});$('#update').onclick=async()=>{if(busy){toast('Esperá a que termine el guardado.');return;}if(dirty&&!await confirmAction('Actualizar la aplicación','Hay cambios sin guardar. ¿Descartarlos y actualizar?'))return;dirty=false;sessionStorage.setItem('mesa-updating','yes');registration.waiting?.postMessage({type:'SKIP_WAITING'});};}catch{status('No se preparó el modo offline');}}
window.addEventListener('online',checkOffline);window.addEventListener('offline',checkOffline);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install').hidden=true;}};
async function start(){try{const names=['foods','recipes','articles','sources','config'];const values=await Promise.all(names.map(async n=>{const r=await fetch(`data/${n}.json`);if(!r.ok)throw Error('No se pudo cargar el contenido. Conectate una vez y recargá.');return r.json();}));catalog=Object.fromEntries(names.map((n,i)=>[n,values[i]]));try{await openDB();const saved=await read();state=saved?validateState(saved):fresh();dbReady=true;}catch(e){$('#storage-error').hidden=false;$('#storage-error').textContent=e.message+' Podés consultar la biblioteca; no se habilitó el guardado. No borres los datos del navegador para solucionar esto.';}applyTheme();$('#date-label').textContent=new Date().toLocaleDateString('es',{weekday:'long',day:'numeric',month:'long'});$('#credit').append('Hecho por ',external(catalog.config.author,catalog.config.authorUrl),' · ',link('Código abierto',catalog.config.repository));render(false);setupPWA();}catch(e){$('#main').replaceChildren(empty('No se pudo cargar la guía',e.message),button('Volver a intentar',()=>location.reload()));status('Contenido no disponible');}}
start();
