// Uses an already available Playwright, never installs browsers or dependencies.
// PLAYWRIGHT_PATH=/absolute/path/to/playwright node tests/e2e.cjs [base-url]
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.argv[2]||'http://127.0.0.1:8765/';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const p=await ctx.newPage();const errors=[],externalRequests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(new URL(base).origin)&&!r.url().startsWith('blob:'))externalRequests.push(r.url());});
 const ok=s=>console.log('PASS',s);
 async function route(hash){await p.evaluate(h=>location.hash=h,hash);await p.waitForTimeout(100);}
 async function confirm(){await p.locator('#confirm button[value=ok]').click();await p.waitForTimeout(150);}
 async function state(){return p.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('mesa-serena-v1',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('state').objectStore('state').get('personal');q.onsuccess=()=>{resolve(q.result);db.close();};q.onerror=()=>reject(q.error);};}));}
 try{
 await p.goto(base);await p.waitForSelector('#daily-form');await p.waitForFunction(()=>document.querySelector('#offline-status').textContent==='Disponible sin conexión');ok('complete offline cache');
 await p.getByLabel('Sumar una verdura',{exact:true}).check();await p.locator('[name=note]').fill('Cena tranquila <img src=x onerror=alert(1)>');await p.locator('summary').click();await p.locator('[name=weight]').fill('80,5');await p.locator('[name=waist]').fill('90');await p.getByRole('button',{name:'Guardar mi día',exact:true}).click();await p.waitForFunction(()=>document.querySelector('button[type=submit]').textContent==='Actualizar mi día');await p.reload();await p.waitForSelector('#daily-form');assert.equal(await p.locator('[name=note]').inputValue(),'Cena tranquila <img src=x onerror=alert(1)>');assert.equal((await state()).entries[0].weight,80.5);ok('diary persists after reload; decimal comma; text safe');
 await p.locator('[name=note]').fill('unsaved');await route('explorar');await p.locator('#confirm button[value=cancel]').click();await p.waitForTimeout(150);assert.ok(await p.locator('#daily-form').count());await route('explorar');await confirm();await p.waitForSelector('#search');ok('unsaved form navigation guard');
 await p.locator('#search').fill('manzana');assert.equal(await p.locator('#results article').count(),1);await p.getByRole('button',{name:'Añadir a favoritos'}).click();assert.ok((await state()).favorites.includes('fdc-171688'));await p.getByRole('link',{name:'Manzana',exact:true}).click();await p.locator('#grams').fill('150');assert.ok((await p.locator('.nutrients').first().innerText()).includes('78 kcal'));ok('search, favorite, source and 150 g apple calculation');
 await route('ajustes');await p.locator('[name=height]').fill('200');await p.getByRole('button',{name:'Guardar preferencias'}).click();await p.waitForTimeout(100);await route('progreso');assert.ok((await p.locator('main').innerText()).includes('20,1'));assert.equal(await p.locator('.chart').count(),2);ok('BMI and dated charts with table');
 await route('registro');await p.locator('[name=date]').fill('2026-01-01');await p.locator('[name=note]').fill('Día anterior');await p.getByRole('button',{name:'Guardar registro',exact:true}).click();await p.waitForTimeout(150);assert.equal((await state()).entries.length,2);ok('add historical date without deleting today');
 await route('ajustes');const before=await state();await p.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"app":"mesa-serena","version":1,"data":{}}')});await p.waitForTimeout(100);assert.deepEqual(await state(),before);ok('invalid import preserves all stored data');
 const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'Exportar respaldo JSON'}).click();await confirm();const download=await downloadPromise;const backupText=fs.readFileSync(await download.path(),'utf8');assert.equal(JSON.parse(backupText).data.entries.length,2);ok('export produces valid backup');
 await p.getByRole('button',{name:'Eliminar todos mis datos',exact:true}).click();await confirm();await p.waitForTimeout(120);assert.equal((await state()).entries.length,0);await p.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backupText)});await confirm();await p.waitForTimeout(150);assert.deepEqual(await state(),before);ok('delete and transactional restore');
 await p.getByLabel('Ocultar peso, cintura y cálculos').check();await p.getByRole('button',{name:'Guardar preferencias'}).click();await p.waitForTimeout(100);await route('progreso');assert.equal(await p.locator('.chart').count(),0);assert.ok(!(await p.locator('main').innerText()).includes('80,5'));assert.equal((await state()).entries.length,2);ok('hide measurements without deleting them');
 await route('habitos');await p.locator('input[type=checkbox]').nth(3).check();await p.getByRole('button',{name:'Guardar hábitos',exact:true}).click();await p.waitForTimeout(100);assert.equal((await state()).habits.length,3);await route('hoy');await confirm();ok('fourth habit rejected');
 await ctx.setOffline(true);await p.reload();await p.waitForSelector('#daily-form');await route('explorar');await p.locator('#search').fill('');assert.equal(await p.locator('#results article').count(),50);await route('receta/recipe-1');assert.ok((await p.locator('main').innerText()).includes('Estimación por porción'));await route('articulo/article-1');assert.ok((await p.locator('main').innerText()).includes('Una base flexible'));ok('offline reload, all foods, recipe, article');await ctx.setOffline(false);
 await route('hoy');await p.getByRole('button',{name:'Cambiar a tema oscuro'}).click();await p.waitForTimeout(80);assert.equal(await p.locator('body').getAttribute('data-theme'),'dark');await p.reload();await p.waitForSelector('#daily-form');assert.equal(await p.locator('body').getAttribute('data-theme'),'dark');ok('dark theme persists');
 for(const width of [390,320]){await p.setViewportSize({width,height:844});for(const hash of ['hoy','explorar','progreso','aprender','ajustes','alimento/fdc-171688','receta/recipe-1']){await route(hash);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${hash} at ${width}`);}}ok('all primary views responsive at 320 and 390 px');
 assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);ok('no runtime errors or external data requests');
 // Failure to install a new cache must not falsely claim readiness; retry online repairs it.
 const failedCtx=await browser.newContext();const failed=await failedCtx.newPage();await failedCtx.route('**/assets/icon-512.png',r=>r.abort());await failed.goto(base);await failed.waitForSelector('#daily-form');await failed.waitForTimeout(1200);assert.notEqual(await failed.locator('#offline-status').innerText(),'Disponible sin conexión');await failedCtx.unroute('**/assets/icon-512.png');await failed.reload();await failed.waitForFunction(()=>document.querySelector('#offline-status').textContent==='Disponible sin conexión');ok('incomplete first download does not claim offline readiness; retry succeeds');await failedCtx.close();
 // IDB rejection: library remains usable and saving never reports success.
 const blockedCtx=await browser.newContext();await blockedCtx.addInitScript(()=>{indexedDB.open=()=>{throw Error('Storage blocked for test');};});const blocked=await blockedCtx.newPage();await blocked.goto(base);await blocked.waitForSelector('#daily-form');await blocked.getByRole('button',{name:'Guardar mi día'}).click();assert.ok((await blocked.locator('#toast').innerText()).includes('No se guardó'));await blocked.evaluate(()=>location.hash='explorar');await blocked.waitForSelector('#results');ok('unavailable storage reports failure and leaves catalog usable');await blockedCtx.close();
 // Clean screenshots contain no personal fixtures.
 const cleanCtx=await browser.newContext({viewport:{width:1440,height:1000}});const clean=await cleanCtx.newPage();await clean.goto(base);await clean.waitForSelector('#daily-form');await clean.waitForFunction(()=>document.querySelector('#offline-status').textContent==='Disponible sin conexión');fs.mkdirSync('docs/screenshots',{recursive:true});await clean.screenshot({path:'docs/screenshots/desktop.png',fullPage:true});await clean.setViewportSize({width:390,height:844});await clean.screenshot({path:'docs/screenshots/mobile.png',fullPage:true});await cleanCtx.close();ok('clean functional screenshots captured');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
