"""Original editorial content. Run only when intentionally regenerating catalog content."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
def save(name,data):(ROOT/'data'/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
save('sources.json',[
 dict(id='who',title='OMS · Alimentación saludable',url='https://www.who.int/news-room/fact-sheets/detail/healthy-diet',year=2026,kind='Recomendaciones poblacionales',reviewed='2026-10-04',limits='Orientación general; no sustituye indicaciones individuales.'),
 dict(id='nice',title='NICE NG246 · Alimentación y actividad física',url='https://www.nice.org.uk/guidance/ng246/chapter/Physical-activity-and-diet',year=2025,kind='Guía clínica',reviewed='2026-10-04',limits='Contexto sanitario británico. No trasladamos sus tratamientos a una app de autocuidado.'),
 dict(id='anthro',title='NICE NG246 · Evaluación antropométrica',url='https://www.nice.org.uk/guidance/ng246/chapter/Identifying-and-assessing-overweight-obesity-and-central-adiposity',year=2025,kind='Guía clínica',reviewed='2026-10-04',limits='El IMC no describe por sí solo la salud. La relación cintura/altura tiene límites de aplicación; no emitimos categorías de riesgo.'),
 dict(id='usda',title='USDA · FoodData Central SR Legacy',url='https://fdc.nal.usda.gov/download-datasets/',year=2018,kind='Base de composición de alimentos',reviewed='2026-10-04',limits='Datos históricos de alimentos de referencia estadounidenses, no análisis de tu comida ni valores de todas las marcas. Por 100 g de parte comestible.'),
 dict(id='privacy',title='GitHub Pages · Alojamiento y registros técnicos',url='https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages',year=2026,kind='Documentación del alojamiento',reviewed='2026-10-04',limits='GitHub registra IP por seguridad. No recibe el diario a través de esta aplicación.')])
R=[]
def recipe(title,desc,minutes,servings,ingredients,steps,tags,allergens,swap):
 R.append(dict(id=f'recipe-{len(R)+1}',name=title,description=desc,minutes=minutes,servings=servings,ingredients=[dict(food='fdc-'+str(f),grams=g) for f,g in ingredients],steps=steps,tags=tags,allergens=allergens,substitution=swap,source='usda',reviewed='2026-10-04'))
recipe('Ensalada tibia de lentejas','Una base sencilla para aprovechar legumbres ya cocidas.',15,2,[(172421,300),(170457,200),(168409,100),(171413,10),(167746,20)],['Usá lentejas previamente cocidas y escurridas. Lavá el tomate, el pepino y el limón.','Cortá el tomate y el pepino. Entibiá las lentejas si lo preferís.','Mezclá con el aceite y la pulpa o jugo del limón. Repartí en dos porciones.'],['Económica','Vegetal'],[],'Podés usar porotos cocidos. La estimación corresponde solo a los ingredientes listados.')
recipe('Avena con banana y nueces','Un desayuno caliente, con ingredientes de todos los días.',12,1,[(169705,40),(173647,160),(173944,100),(170187,15)],['Cociná la avena en el agua siguiendo el tiempo de cocción del envase. Agregá agua si hace falta.','Cortá la banana sin cáscara.','Serví la avena con la banana y las nueces picadas.'],['Desayuno','Vegetal'],['Nueces','Avena: verificar gluten y contaminación cruzada'],'Cambiá la banana por pera. Revisá alergias antes de sustituir frutos secos.')
recipe('Tostada de palta y huevo','Para resolver una comida breve con una preparación conocida.',15,1,[(172688,80),(171705,70),(173424,50),(170457,80)],['Usá un huevo completamente cocido; pelalo y pesá la parte comestible.','Tostá el pan. Pisá la palta y lavá y cortá el tomate.','Armá las tostadas con palta, tomate y huevo.'],['Rápida'],['Trigo / gluten','Huevo'],'Podés servir los ingredientes con papa cocida en lugar de pan; los valores cambian.')
recipe('Bowl de quinoa y garbanzos','Colores y texturas para comer a tu ritmo.',15,2,[(168917,250),(173757,250),(170108,100),(168409,100),(171413,10),(167746,20)],['Partí de quinoa y garbanzos ya cocidos.','Lavá el morrón, el pepino y el limón. Cortá las verduras pequeñas.','Mezclá todo con aceite y limón y dividí en dos platos.'],['Vegetal','Para llevar'],[],'El arroz cocido puede reemplazar a la quinoa, con una composición diferente.')
recipe('Crema suave de calabaza','Una preparación cálida, sin pasos complicados.',15,2,[(168449,400),(170440,200),(173647,300),(171413,10)],['Usá calabaza y papa ya hervidas y escurridas, en los pesos indicados.','Calentalas con el agua hasta que estén bien calientes.','Pisá o procesá con cuidado. Añadí el aceite y ajustá la textura con agua.'],['Económica','Vegetal'],[],'Podés variar la proporción de papa y calabaza; la estimación dejará de ser la indicada.')
recipe('Yogur con frutillas y almendras','Una idea fresca para desayuno o colación.',5,1,[(171284,170),(167762,120),(170567,15)],['Lavá las frutillas y retirales las hojas.','Cortalas y mezclalas con el yogur.','Agregá las almendras picadas justo antes de servir.'],['Sin cocción','Rápida'],['Leche','Almendras'],'Usá una alternativa vegetal apropiada si la necesitás; su composición puede ser muy distinta.')
recipe('Arroz integral con pollo y brócoli','Una forma de combinar preparaciones que ya tenés listas.',12,2,[(169704,300),(171477,200),(169967,250),(171413,10)],['Usá arroz cocido, pollo completamente asado y brócoli hervido; los pesos son después de cocinar.','Cortá el pollo. Calentá los tres ingredientes de forma uniforme y completa.','Añadí el aceite y repartí. Usá preparaciones conservadas adecuadamente en frío.'],['Comida principal'],[],'Podés reemplazar el pollo por tofu; comprobá soja y otras alergias. Los valores cambiarán.')
recipe('Ensalada de papa y atún','Una combinación práctica sin cocinar desde cero.',12,2,[(170440,300),(171986,180),(170457,150),(171413,10),(167746,20)],['Partí de papa ya hervida y atún en agua escurrido.','Lavá y cortá el tomate y el limón.','Mezclá la papa en cubos con el atún, tomate, aceite y limón. Serví o refrigerá pronto.'],['Rápida','Comida principal'],['Pescado'],'Garbanzos cocidos pueden reemplazar al atún; recalculá si necesitás los valores.')
recipe('Boniato con porotos negros','Dos preparaciones simples que se encuentran en el plato.',12,2,[(168484,300),(173735,300),(170457,150),(171413,10)],['Usá boniato hervido sin piel y porotos ya cocidos.','Lavá y cortá el tomate.','Calentá boniato y porotos. Serví con tomate y aceite.'],['Vegetal','Económica'],[],'Lentejas cocidas son otra opción, con valores nutricionales diferentes.')
recipe('Ensalada de cebada y arvejas','Una idea para variar los cereales de la semana.',12,2,[(170285,300),(170420,200),(170108,100),(171413,10),(167746,20)],['Usá cebada y arvejas previamente cocidas.','Lavá el morrón y el limón; cortá el morrón.','Mezclá con el aceite y el limón. Serví tibia o enfriá y refrigerá pronto.'],['Vegetal','Para llevar'],['Cebada / gluten'],'La quinoa cocida permite otra variante; las estimaciones corresponden a la cebada.')
save('recipes.json',R)
articles=[
('Una alimentación que se adapte a vos','Empezar por variedad, no por perfección.','who',[
('Una base flexible','La OMS propone diversidad, equilibrio, moderación y adecuación como principios generales. Frutas, verduras, legumbres y cereales integrales pueden formar parte de esa variedad. No hace falta que cada comida sea idéntica ni que una sola comida represente toda tu alimentación.'),
('Una idea para probar','Como propuesta práctica de esta app, mirá una comida habitual y pensá qué podrías sumar o variar con lo que ya tenés. Puede ser una verdura disponible o una preparación que te resulte sencilla. Esta actividad es una sugerencia editorial, no una pauta clínica.'),
('Tu contexto importa','Anotá qué opciones te gustan, cuánto tiempo tenés y qué alimentos podés conseguir. No necesitás comprar productos especiales para usar esta guía. Las preferencias, la cultura y el presupuesto forman parte de las decisiones cotidianas.')]),
('Entender el balance energético','Una explicación, no una meta de calorías.','nice',[
('Qué significa','El balance energético relaciona la energía que entra con la que el cuerpo utiliza. NICE contempla diferentes enfoques para reducir la ingesta energética en el tratamiento del peso, con apoyo y seguimiento. Esta app no calcula un déficit ni prescribe una dieta.'),
('Lo que no dice una cifra','Una estimación de energía de un alimento no es una instrucción sobre cuánto debés comer. Tampoco predice cuánto va a cambiar tu peso. Los datos de la guía representan alimentos de referencia, no una medición de tu plato.'),
('Cómo usar esta información','Podés consultar una ficha para conocer un ingrediente y luego cerrar la pantalla sin llevar una cuenta diaria. Si necesitás un plan de reducción de peso adaptado a tu salud, consultá a un profesional. Aquí priorizamos observación y pequeños hábitos elegidos por vos.')]),
('Porciones sin reglas rígidas','Los gramos de la guía son ejemplos de cálculo.','usda',[
('Una referencia comparable','Las fichas parten de datos por 100 gramos de parte comestible. El selector permite calcular otra cantidad. La porción inicial es un ejemplo editorial, no una recomendación sobre lo que necesitás comer.'),
('Antes o después de cocinar','Revisá siempre el estado del alimento: arroz seco y arroz cocido no son la misma referencia. En las recetas de esta app, cada ingrediente indica el estado al que corresponde su peso. No reemplaces uno por otro esperando el mismo resultado.'),
('Una herramienta opcional','Si querés aprender cómo se ve una cantidad, podés pesarla una vez y observarla. No es necesario pesar cada comida ni usar una balanza para registrar hábitos. Tampoco usamos categorías de alimentos buenos o malos.'),
('Límites del cálculo','Variedad, marca, preparación y agua retenida pueden cambiar la composición. Los números se muestran redondeados. Si falta un dato, indicamos «Sin dato» en lugar de inventar un cero.')]),
('Fibra y variedad en el plato','Reconocer alimentos que la aportan.','who',[
('Dónde encontrarla','Frutas, verduras, legumbres y cereales integrales son fuentes alimentarias de fibra. La orientación de la OMS favorece estos grupos dentro de una alimentación variada.'),
('Una exploración sencilla','Como ejercicio opcional, buscá en la guía una legumbre que conozcas y una que no suelas preparar. Mirá su estado de cocción y alguna receta que la utilice. Podés guardar una idea en favoritos para otro día; consultarla no te compromete a cambiar toda tu alimentación.'),
('Sin convertirlo en una competencia','No añadimos un objetivo automático de gramos de fibra. La ficha es informativa y no debe usarse para ajustar tratamientos digestivos. Si tenés una indicación clínica o molestias persistentes, pedí orientación individual antes de hacer cambios importantes.')]),
('Hambre, saciedad y atención','Observar sin puntuarse.','nice',[
('Un espacio para describir','La nota del diario puede servir para escribir cómo fue una comida: si tuviste tiempo, si te gustó o si te resultó práctica. No necesitás asignarte una nota ni justificar lo que comiste. Esta es una opción de diseño de Mesa Serena, no una intervención validada.'),
('No clasificamos la saciedad','No asignamos a cada alimento una puntuación universal de saciedad. Sería una simplificación que no podemos defender para todas las personas y situaciones. Tampoco usamos el hambre como prueba de éxito ni sugerimos ignorarla.'),
('Elegí cuánto registrar','Podés dejar la nota vacía, ocultar las mediciones o usar solo la biblioteca. Si el registro genera preocupación, culpa o necesidad de compensar comidas, dejá de usar esa función y buscá apoyo profesional. Esta guía no está diseñada para tratar trastornos alimentarios.')]),
('Planificar con lo que tenés','Menos decisiones, una comida por vez.','who',[
('Un ejercicio de organización','Elegí una comida de mañana. Revisá qué ingredientes hay y qué tiempo tenés disponible. Anotá una opción sencilla. Este ejercicio es una propuesta editorial para organizarte; no promete resultados sobre el peso.'),
('Un pequeño inventario','Podés escribir tres listas breves: alimentos que ya tenés, preparaciones que sabés hacer y productos que faltan. Si una receta requiere demasiadas compras, guardala para otra ocasión y buscá una alternativa.'),
('Dejar lugar a cambios','Un plan puede cambiar. Si no cocinaste lo previsto, el diario sigue disponible al día siguiente sin reiniciar rachas ni mostrar castigos. Elegí hábitos que te resulten útiles y modificá los que ya no tengan sentido.'),
('Seguridad cotidiana','Revisá fechas y condiciones de conservación de los envases. Las recetas no sustituyen las indicaciones de seguridad de cada producto. Los tiempos mostrados suponen que los ingredientes descritos como cocidos ya están preparados.')]),
('Leer tu progreso con calma','Una medición no resume tu salud.','anthro',[
('Qué muestra la app','El gráfico muestra los valores que registraste en sus fechas reales. La tabla permite leerlos sin depender de colores. No calculamos una fecha objetivo ni calificamos subir o bajar como éxito o fracaso.'),
('IMC y cintura/altura','El IMC divide peso en kilogramos por altura en metros al cuadrado. La relación cintura/altura utiliza ambas medidas en la misma unidad. Son cálculos informativos: el IMC no distingue grasa de músculo y no describe por sí solo la salud individual.'),
('Límites de interpretación','NICE utiliza cintura/altura junto con otras evaluaciones, en particular en adultos con IMC inferior a 35. No mostramos categorías de riesgo ni diagnósticos. Estos cálculos no son apropiados para interpretar embarazo ni sustituyen una evaluación personal.'),
('Otras formas de observar','También podés mirar qué hábitos registraste. El porcentaje se calcula sobre hábitos planificados en días con registro, no sobre días que dejaste en blanco. Ausencia de datos no significa incumplimiento.')]),
('Cuándo buscar orientación','Conocer los límites también es autocuidado.','nice',[
('Para quién es esta guía','Mesa Serena ofrece educación general para adultos. No es un tratamiento de la obesidad, una consulta ni un sistema de detección de enfermedades. Tener acceso a una ficha no significa que esa preparación sea adecuada para una situación clínica específica.'),
('Situaciones que necesitan otro acompañamiento','No ofrecemos pautas para menores, embarazo, lactancia, trastornos alimentarios, cirugía bariátrica ni enfermedades con necesidades nutricionales particulares. Si tenés una indicación médica, no la cambies por lo que leas aquí.'),
('Pedir ayuda','Ante cambios de peso involuntarios, malestar persistente o preocupación por la relación con la comida, consultá a un profesional sanitario. Ante una urgencia, acudí a los servicios de tu localidad; esta app no evalúa síntomas ni tiene seguimiento humano.'),
('Cómo se revisó','El contenido tiene fuentes y revisión documental, no revisión clínica independiente. Podés consultar las referencias y reportar un error sin compartir datos personales. La fecha de revisión no significa que hayamos comprobado que la app mejora resultados de salud.')])]
save('articles.json',[dict(id=f'article-{i+1}',name=t,description=d,source=s,sections=[dict(title=h,text=p) for h,p in sections],reviewed='2026-10-04',reviewDue='2027-10-04',status='Revisión documental',minutes=2) for i,(t,d,s,sections) in enumerate(articles)])
save('config.json',dict(name='Mesa Serena',author='Martín Martínez García (Bluffer)',authorUrl='https://github.com/MartnMartnez14',supportUrl=None,repository='https://github.com/MartnMartnez14/mesa-serena',version='1.0.0'))
