"""Update the static offline manifest after changing shipped application files."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[1]
paths=['index.html','styles.css','manifest.webmanifest']+[str(p.relative_to(root)) for folder in ['js','data','assets'] for p in sorted((root/folder).glob('*')) if p.is_file()]
version=hashlib.sha256(b''.join((root/p).read_bytes() for p in paths)).hexdigest()[:12]
header='// Generated by scripts/update_cache.py. Change content then regenerate.\nconst VERSION = '+json.dumps(version)+';\nconst FILES = '+json.dumps(['./']+paths,indent=2)+';\n'
(root/'sw.js').write_text(header+(root/'scripts/sw-template.js').read_text())
print('Offline manifest:',len(paths)+1,'resources; version',version)
